apiVersion: v1
kind: Secret
metadata:
  name: pan-mgmt-secret
  namespace: kube-system
type: Opaque
stringData:
 # Panorama Auth Key
  PAN_PANORAMA_AUTH_KEY: "<<changeme>>"
  # Thermite Certificate retrieval 
  CN-SERIES-AUTO-REGISTRATION-PIN-ID: ""
  CN-SERIES-AUTO-REGISTRATION-PIN-VALUE: ""
#Non-mandatory parameters
  # Uncomment this for CSP overide 
  #CN-SERIES-AUTO-REGISTRATION-API-CSP: "<csp-url>" 
